### ISSUE TITLE
Should transparent values count?

### ISSUE THREAD

**Issue by YoungElPaso** [johno/get-contrast#3]
So I noticed that an rgba value of (0, 0, 0, 0) contrasted well with say 'white'.  This seems odd.  Should a color be contrasted with a transparent color? This seems counter-intuitive.  I'll make a pull request to exclude colors with a transparency value of '0' from the comparison and throw an error.

**Comment by johno** [comment]
Published to npm as `get-contrast@2.0.0`. Thanks for your contribution!
